"""Allow `python -m wazuh_mcp` to launch the server.

Sub-commands:
  (no args)        — start the MCP server (default)
  init             — interactive setup wizard, writes a .env file
  verify           — test connectivity to Manager and Indexer from .env
"""
from __future__ import annotations

import sys


def _cmd_init() -> None:
    """Interactive setup wizard — writes a .env file in the current directory."""
    import os
    import getpass

    print("\n╔══════════════════════════════════════════════════════╗")
    print("║          Wazuh MCP Server — Setup Wizard             ║")
    print("╚══════════════════════════════════════════════════════╝\n")

    env_path = os.path.join(os.getcwd(), ".env")
    if os.path.exists(env_path):
        overwrite = input(f".env already exists at {env_path}. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Aborted. Existing .env unchanged.")
            sys.exit(0)

    print("Choose deployment type:")
    print("  1) Self-hosted Wazuh (on-prem / VM / Docker)")
    print("  2) Wazuh Cloud")
    print("  3) MSSP / Multi-tenant (multiple Wazuh instances)")
    choice = input("\nEnter 1, 2, or 3 [default: 1]: ").strip() or "1"

    lines: list[str] = [
        "# Generated by: wazuh-mcp init",
        "# Edit this file to adjust any values, then start with: wazuh-mcp",
        "",
    ]

    if choice == "2":
        lines += _wizard_cloud()
    elif choice == "3":
        lines += _wizard_mssp()
    else:
        lines += _wizard_selfhosted()

    # Common settings
    print("\n── MCP Transport ──────────────────────────────────────")
    transport = input("Transport mode [http/stdio, default: http]: ").strip() or "http"
    lines += [
        "# MCP Server Transport",
        f"WAZUH_MCP_TRANSPORT={transport}",
    ]
    if transport == "http":
        host = input("Bind host [default: 0.0.0.0]: ").strip() or "0.0.0.0"
        port = input("Port [default: 8000]: ").strip() or "8000"
        lines += [
            f"WAZUH_MCP_HOST={host}",
            f"WAZUH_MCP_PORT={port}",
        ]
        api_key = getpass.getpass("MCP API key (leave blank to disable auth): ").strip()
        if api_key:
            lines.append(f"WAZUH_MCP_API_KEY={api_key}")

    print("\n── SSL / TLS ──────────────────────────────────────────")
    verify = input("Verify SSL certificates? [Y/n, default: y]: ").strip().lower() or "y"
    lines.append(f"WAZUH_VERIFY_SSL={'true' if verify != 'n' else 'false'}")
    if verify == "n":
        print("  ⚠  SSL verification disabled — only safe for dev/lab environments.")

    print("\n── Optional: Threat Intelligence ──────────────────────")
    vt_key = getpass.getpass("VirusTotal API key (leave blank to skip): ").strip()
    if vt_key:
        lines.append(f"VIRUSTOTAL_API_KEY={vt_key}")
    ab_key = getpass.getpass("AbuseIPDB API key (leave blank to skip): ").strip()
    if ab_key:
        lines.append(f"ABUSEIPDB_API_KEY={ab_key}")

    print("\n── Optional: Notifications ─────────────────────────────")
    slack = input("Slack webhook URL (leave blank to skip): ").strip()
    if slack:
        lines.append(f"SLACK_WEBHOOK_URL={slack}")

    # Write credentials to .env with owner-only permissions (0o600).
    # Writing user-supplied credentials here is the explicit purpose of the init
    # wizard — this is not a secret-leakage bug. File mode 0o600 restricts access.
    import os as _os
    fd = _os.open(env_path, _os.O_WRONLY | _os.O_CREAT | _os.O_TRUNC, 0o600)
    # Force UTF-8: generated comment lines contain box-drawing/em-dash glyphs
    # that the platform default (cp1252 on Windows) cannot encode.
    with _os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\n✓ .env written to: {env_path}")
    print("\nNext steps:")
    print("  1. Review and adjust the .env file if needed")
    print("  2. Run: wazuh-mcp verify    (test connectivity)")
    print("  3. Run: wazuh-mcp           (start the server)")
    print("\nFor Claude Desktop, add this to your MCP config:")
    if transport == "http":
        # Extract only the non-sensitive port value; never print credential lines.
        import re as _re
        port_val = "8000"
        for line in lines:
            m = _re.match(r"^WAZUH_MCP_PORT=(\d+)$", line)
            if m:
                port_val = m.group(1)
                break
        print(f'  {{"mcpServers": {{"wazuh": {{"url": "http://localhost:{port_val}/sse"}}}}}}')
    else:
        print('  {"mcpServers": {"wazuh": {"command": "wazuh-mcp"}}}')
    print()


def _wizard_selfhosted() -> list[str]:
    lines = [
        "# ── Wazuh Manager API ─────────────────────────────────",
    ]
    print("\n── Wazuh Manager ──────────────────────────────────────")
    host = input("Manager URL [e.g. https://192.168.1.10:55000]: ").strip()
    user = input("Manager API username [default: wazuh-wui]: ").strip() or "wazuh-wui"
    import getpass
    pw = getpass.getpass("Manager API password: ").strip()
    lines += [f"WAZUH_HOST={host}", f"WAZUH_USER={user}", f"WAZUH_PASS={pw}", ""]

    print("\n── Wazuh Indexer (OpenSearch) ─────────────────────────")
    idx_host = input(f"Indexer URL [default: {host.replace(':55000', ':9200')}]: ").strip() or host.replace(":55000", ":9200")
    idx_user = input("Indexer username [default: wazuh-readonly]: ").strip() or "wazuh-readonly"
    idx_pw = getpass.getpass("Indexer password: ").strip()
    lines += [
        "# ── Wazuh Indexer ─────────────────────────────────────",
        f"WAZUH_INDEXER_HOST={idx_host}",
        f"WAZUH_INDEXER_USER={idx_user}",
        f"WAZUH_INDEXER_PASS={idx_pw}",
        "",
    ]
    return lines


def _wizard_cloud() -> list[str]:
    import getpass
    print("\n── Wazuh Cloud ────────────────────────────────────────")
    print("Find your Cloud URL in the Wazuh Cloud console under 'API Credentials'.")
    cloud_url = input("Wazuh Cloud API URL [e.g. https://xxx.cloud.wazuh.com:55000]: ").strip()
    api_key = getpass.getpass("Wazuh Cloud API key: ").strip()
    idx_pass = getpass.getpass("Wazuh Cloud Indexer password (admin): ").strip()
    return [
        "# ── Wazuh Cloud ───────────────────────────────────────",
        "WAZUH_CLOUD=true",
        f"WAZUH_CLOUD_URL={cloud_url}",
        f"WAZUH_CLOUD_API_KEY={api_key}",
        f"WAZUH_CLOUD_INDEXER_PASS={idx_pass}",
        "",
    ]


def _wizard_mssp() -> list[str]:
    import getpass, json
    print("\n── MSSP Multi-Tenant Setup ────────────────────────────")
    print("You will be prompted to enter details for each tenant (Wazuh instance).")
    print("Press Enter with no name to finish adding tenants.\n")

    instances = []
    while True:
        name = input(f"Tenant name (e.g. client-a) [Enter to finish]: ").strip()
        if not name:
            break
        host = input(f"  Manager URL for '{name}': ").strip()
        user = input(f"  Manager user [default: wazuh-wui]: ").strip() or "wazuh-wui"
        pw = getpass.getpass(f"  Manager password: ").strip()
        idx_host = input(f"  Indexer URL [default: {host.replace(':55000',':9200')}]: ").strip() or host.replace(":55000", ":9200")
        idx_pw = getpass.getpass(f"  Indexer password: ").strip()
        instances.append({
            "name": name,
            "host": host,
            "user": user,
            "pass": pw,
            "indexer_host": idx_host,
            "indexer_pass": idx_pw,
        })
        print(f"  ✓ Added tenant '{name}'\n")

    if not instances:
        print("No tenants added. Falling back to self-hosted wizard.")
        return _wizard_selfhosted()

    # Use first tenant as the default connection too
    first = instances[0]
    lines = [
        "# ── MSSP Mode: default connection = first tenant ──────",
        f"WAZUH_HOST={first['host']}",
        f"WAZUH_USER={first['user']}",
        f"WAZUH_PASS={first['pass']}",
        f"WAZUH_INDEXER_HOST={first['indexer_host']}",
        "WAZUH_INDEXER_USER=wazuh-readonly",
        f"WAZUH_INDEXER_PASS={first['indexer_pass']}",
        "",
        "# All tenants (used by switch_tenant tool)",
        f"WAZUH_INSTANCES={json.dumps(instances)}",
        "",
    ]
    return lines


def _cmd_verify() -> None:
    """Test connectivity to Manager and Indexer using the current .env."""
    import os, asyncio, httpx
    from pathlib import Path

    env_path = Path(".env")
    if env_path.exists():
        from dotenv import load_dotenv
        load_dotenv(env_path)
        print(f"Loaded .env from {env_path.resolve()}")
    else:
        print("No .env found — using environment variables")

    try:
        from .config import Config
        cfg = Config.from_env()
    except RuntimeError as e:
        print(f"\n✗ Configuration error: {e}")
        print("  Run 'wazuh-mcp init' to create a .env file.")
        sys.exit(1)

    print(f"\nTesting Manager:  {cfg.manager_host}")
    print(f"Testing Indexer:  {cfg.indexer_host}")
    if cfg.cloud_mode:
        print("Mode: Wazuh Cloud")
    if cfg.tenants:
        print(f"MSSP tenants configured: {len(cfg.tenants)}")

    async def _check():
        results = {}
        async with httpx.AsyncClient(verify=cfg.verify_ssl, timeout=10) as client:
            # Manager
            try:
                r = await client.get(
                    f"{cfg.manager_host}/",
                    auth=(cfg.manager_user, cfg.manager_pass),
                )
                if r.status_code == 200:
                    ver = r.json().get("data", {}).get("api_version", "unknown")
                    results["manager"] = f"✓ OK  (API version: {ver})"
                else:
                    results["manager"] = f"✗ HTTP {r.status_code}"
            except Exception as e:
                results["manager"] = f"✗ {e}"

            # Indexer
            try:
                r = await client.get(
                    f"{cfg.indexer_host}/_cluster/health",
                    auth=(cfg.indexer_user, cfg.indexer_pass),
                )
                if r.status_code == 200:
                    status = r.json().get("status", "unknown")
                    nodes = r.json().get("number_of_nodes", "?")
                    results["indexer"] = f"✓ OK  (cluster: {status}, nodes: {nodes})"
                else:
                    results["indexer"] = f"✗ HTTP {r.status_code}"
            except Exception as e:
                results["indexer"] = f"✗ {e}"

        return results

    results = asyncio.run(_check())
    print(f"\n  Manager:  {results['manager']}")
    print(f"  Indexer:  {results['indexer']}")

    all_ok = all("✓" in v for v in results.values())
    if all_ok:
        print("\n✓ All systems reachable. Ready to start with: wazuh-mcp\n")
    else:
        print("\n✗ One or more systems unreachable.")
        print("  Check your credentials, host URLs, and SSL settings in .env\n")
        sys.exit(1)


def main() -> None:
    args = sys.argv[1:]

    if args and args[0] == "init":
        _cmd_init()
        return

    if args and args[0] == "verify":
        _cmd_verify()
        return

    # Default: start the MCP server
    from .server import main as _server_main
    _server_main()


if __name__ == "__main__":
    main()
